powerpc/pasemi: mark pas_shutdown() static
mainline inclusion
from mainline-v6.8
category: cleanup

Allmodconfig builds show a warning about one function that is accidentally
marked global:

arch/powerpc/platforms/pasemi/setup.c:67:6: error: no previous prototype for 'pas_shutdown' [-Werror=missing-prototypes]

Fixes: 656fdf3ad8e0 ("powerpc/pasemi: Add Nemo board device init code.")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://msgid.link/20231108125843.3806765-19-arnd@kernel.org

(cherry picked from commit 0c9a768de64d24e38e27652b8c273725ccc31916)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>