net: stmmac: phytium: remove support for lpi_intr_o
[net: stmmac: phytium: remove lpi_irq
        commit 8096f0383425 ("net: stmmac: remove support for lpi_intr_o") upstream,
        so remove it.
        Log:
        drivers/net/ethernet/stmicro/stmmac/dwmac-phytium.c: In function ‘phytium_dwmac_probe’:
        drivers/net/ethernet/stmicro/stmmac/dwmac-phytium.c:188:19: error: ‘struct stmmac_resources’ has no member named ‘lpi_irq’
        188 |         stmmac_res.lpi_irq = -1;]
Log:
drivers/net/ethernet/stmicro/stmmac/dwmac-phytium.c:197:19: error: ‘struct stmmac_resources’ has no member named ‘lpi_irq’
  197 |         stmmac_res.lpi_irq = -1;

Signed-off-by: Wentao Guan <guanwentao@uniontech.com>