tpm: hygon: Add bufsiz parameter to tpm_c_send()
This is hygon version of this commit:
commit a727bc0588e77efb502c52d7356e8ed036b6a83e
Author: Nathan Chancellor <nathan@kernel.org>
Date:   Wed Sep 17 10:09:00 2025 -0700

    tpm: loongson: Add bufsiz parameter to tpm_loongson_send()

    Commit 5c83b07df9c5 ("tpm: Add a driver for Loongson TPM device") has a
    semantic conflict with commit 07d8004d6fb9 ("tpm: add bufsiz parameter
    in the .send callback"), as the former change was developed against a
    tree without the latter change. This results in a build error:

      drivers/char/tpm/tpm_loongson.c:48:17: error: initialization of 'int (*)(struct tpm_chip *, u8 *, size_t,  size_t)' {aka 'int (*)(struct tpm_chip *, unsigned char *, long unsigned int,  long unsigned int)'} from incompatible pointer type 'int (*)(struct tpm_chip *, u8 *, size_t)' {aka 'int (*)(struct tpm_chip *, unsigned char *, long unsigned int)'} [-Wincompatible-pointer-types]
         48 |         .send = tpm_loongson_send,
            |                 ^~~~~~~~~~~~~~~~~
      drivers/char/tpm/tpm_loongson.c:48:17: note: (near initialization for 'tpm_loongson_ops.send')
      drivers/char/tpm/tpm_loongson.c:31:12: note: 'tpm_loongson_send' declared here
         31 | static int tpm_loongson_send(struct tpm_chip *chip, u8 *buf, size_t count)
            |            ^~~~~~~~~~~~~~~~~

    Add the expected bufsiz parameter to tpm_loongson_send() to resolve the
    error.

    Fixes: 5c83b07df9c5 ("tpm: Add a driver for Loongson TPM device")
    Signed-off-by: Nathan Chancellor <nathan@kernel.org>
    Reviewed-by: Jarkko Sakkinen <jarkko@kernel.org>
    Signed-off-by: Lee Jones <lee@kernel.org>

Log:
drivers/char/tpm/tpm_hygon.c:92:17: error: initialization of ‘int (*)(struct tpm_chip *, u8 *, size_t,  size_t)’ {aka ‘int (*)(struct tpm_chip *, unsigned char *, long unsigned int,  long unsigned int)’} from incompatible pointer type ‘int (*)(struct tpm_chip *, u8 *, size_t)’ {aka ‘int (*)(struct tpm_chip *, unsigned char *, long unsigned int)’} [-Werror=incompatible-pointer-types]
   92 |         .send = tpm_c_send,

Link: https://github.com/deepin-community/kernel/pull/366
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>