net: stmmac: phytium: replace has_xxxx with core_type
deepin inclusion
category: bugfix

commit 7b1344d86a4e ("net: stmmac: replace has_xxxx with core_type") upstream
in v6.18.14,so phytium glue driver will built failed.

Log:
2026-03-09T11:14:17.5250109Z drivers/net/ethernet/stmicro/stmmac/dwmac-phytium.c: In function ‘phytium_dwmac_probe’:
2026-03-09T11:14:17.5316620Z drivers/net/ethernet/stmicro/stmmac/dwmac-phytium.c:100:13: error: ‘struct plat_stmmacenet_data’ has no member named ‘has_gmac’
2026-03-09T11:14:17.5325080Z   100 |         plat->has_gmac = 1;
2026-03-09T11:14:17.5354589Z       |             ^~
2026-03-09T11:14:17.6405078Z   LD [M]  drivers/vfio/pci/vfio-pci-core.o
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>