gpio: gpio-phytium-sgpio: Adapt to >= 6.17
Log:
drivers/gpio/gpio-phytium-sgpio.c:279:15: error: incompatible function pointer types assigning to 'int (*)(struct gpio_chip *, unsigned int, int)' from 'void (struct gpio_chip *, unsigned int, int)' [-Wincompatible-function-pointer-types]
  279 |         gpio->gc.set = phytium_sgpio_set;

Fixes: 2a57acffcb35 ("gpio: gpio-phytium-sgpio: Add Phytium SGPIO driver") # v6.18
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>