LOONGSON: irqchip/loongson-eiointc: Improve IRQ affinity setting
On multiple bridge platform, a MSIX vector is often affinitive with only
one cpu, and the count of MSIX is determined as the count of cpus in the
system. Unfortunately, the cpu group related to a brigde is only allowed
to handle interrupts from devices behind the bridge, which breaks the
normal affinity setting for multiple MSIX vectors, and causing following
affinity setting:

IRQ: 4, 5, 6, 7, 8, 9, 10, 11, 12, 13
CPU: 0, 1, 2, 3, 4, 0,  0,  0,  0,  0

To balance the affinity, we improve the setting to assign cpu for IRQ as
following:

IRQ: 4, 5, 6, 7, 8, 9, 10, 11, 12, 13
CPU: 0, 1, 2, 3, 4, 0,  1,  2,  3,  4

Signed-off-by: Jianmin Lv <lvjianmin@loongson.cn>
Signed-off-by: Huacai Chen <chenhuacai@loongson.cn>

Link: https://github.com/chenhuacai/linux/commit/0e32ff9bd234126ef760127830cacc99a6b71185
Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
Signed-off-by: Mingcong Bai <jeffbai@aosc.io>
Log:
Fix the warning,
drivers/irqchip/irq-loongson-eiointc.c: In function ‘eiointc_set_irq_affinity’:
drivers/irqchip/irq-loongson-eiointc.c:176:25: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
  176 |                         if (c == cpu) break; idx++;
      |                         ^~
drivers/irqchip/irq-loongson-eiointc.c:176:46: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  176 |                         if (c == cpu) break; idx++;
(cherry picked from commit ae08d68869165be8d73c43151a2ff65fe68bd88d)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>