usb: phytium: Fix wrong assign logic in hostErrorIrq
We'll apply a bitwise AND to the controller's rxerrirq and rxerrien
to isolate interrupts that are both triggered and enabled.
This filtering ensures that we only process relevant interrupts.

Self bitwise AND operations are meaningless.

Fix follow error with clang-19:

drivers/usb/phytium/host.c:451:11: error: explicitly assigning value of variable of type 'uint16_t' (aka 'unsigned short') to itself [-Werror,-Wself-assign]
  451 |         rxerrirq &= rxerrirq;
      |         ~~~~~~~~ ^  ~~~~~~~~
1 error generated.

Signed-off-by: WangYuli <wangyuli@uniontech.com>
Link: https://github.com/deepin-community/kernel/pull/504
(cherry picked from commit 42ad1dc65fbbf3ff4583bae121cf30d343fbec6b)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>