tpm: hygon: don't bother with removal of files in directory we'll be removing
In the following commit changed the tpm_chip struct, so modifiy hygon tcm:
commit f42b8d78dee77107245ec5beee3eb01915bcae7f
Author: Al Viro <viro@zeniv.linux.org.uk>
Date:   Wed Jun 11 19:40:04 2025 -0400

    tpm: don't bother with removal of files in directory we'll be removing

    FWIW, there is a reliable indication of removal - ->i_nlink going to 0 ;-)

    Signed-off-by: Al Viro <viro@zeniv.linux.org.uk>

Log:
drivers/char/tpm/tcm_hygon.c: In function ‘tcm_bios_log_teardown’:
drivers/char/tpm/tcm_hygon.c:109:21: error: used struct type value where scalar is required
  109 |                 if (chip->bios_dir[i]) {
      |                     ^~~~
drivers/char/tpm/tcm_hygon.c:110:55: error: incompatible type for argument 1 of ‘d_inode’
  110 |                         inode = d_inode(chip->bios_dir[i]);
      |                                         ~~~~~~~~~~~~~~^~~
      |                                                       |
      |                                                       struct dentry
In file included from ./include/linux/fs.h:9,
                 from ./include/linux/compat.h:17,
                 from ./arch/x86/include/asm/ia32.h:7,
                 from ./arch/x86/include/asm/elf.h:10,
                 from ./include/linux/elf.h:6,
                 from ./include/linux/module.h:20,
                 from drivers/char/tpm/tcm_hygon.c:13:
./include/linux/dcache.h:530:58: note: expected ‘const struct dentry *’ but argument is of type ‘struct dentry’
  530 | static inline struct inode *d_inode(const struct dentry *dentry)
      |                                     ~~~~~~~~~~~~~~~~~~~~~^~~~~~
drivers/char/tpm/tcm_hygon.c:114:57: error: incompatible type for argument 1 of ‘securityfs_remove’
  114 |                         securityfs_remove(chip->bios_dir[i]);
      |                                           ~~~~~~~~~~~~~~^~~
      |                                                         |
      |                                                         struct dentry
In file included from drivers/char/tpm/tcm_hygon.c:22:
./include/linux/security.h:2229:46: note: expected ‘struct dentry *’ but argument is of type ‘struct dentry’
 2229 | extern void securityfs_remove(struct dentry *dentry);
      |                               ~~~~~~~~~~~~~~~^~~~~~
make[5]: *** [scripts/Makefile.build:287：drivers/char/tpm/tcm_hygon.o]

Link: https://github.com/deepin-community/kernel/pull/366
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>