can: phytium: Use phytium_can_of_ids only when CONFIG_OF enabled
Fix follow errors:

drivers/net/can/phytium/phytium_can_platform.c: In function ‘phytium_can_plat_probe’:
drivers/net/can/phytium/phytium_can_platform.c:113:41: error: ‘phytium_can_of_ids’ undeclared (first use in this function); did you mean ‘phytium_can_acpi_ids’?
  113 |                 of_id = of_match_device(phytium_can_of_ids, &pdev->dev);
      |                                         ^~~~~~~~~~~~~~~~~~
      |                                         phytium_can_acpi_ids
drivers/net/can/phytium/phytium_can_platform.c:113:41: note: each undeclared identifier is reported only once for each function it appears in

Signed-off-by: WangYuli <wangyuli@uniontech.com>
Link: https://github.com/deepin-community/kernel/pull/374
(cherry picked from commit 759f31a09a18e826e6cd48bb85f898aabf8c8911)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>