deepin: drivers: net: wwan: Fix simple DTR driver build for v6.18
deepin inclusion
category: bugfix

Log:
2026-03-03T18:33:59.0448519Z drivers/net/wwan/mhi_wwan_dtr.c:13:5: error: no previous prototype for ‘mhi_wwan_dtr_set’ [-Werror=missing-prototypes]
2026-03-03T18:33:59.0450319Z    13 | int mhi_wwan_dtr_set(struct wwan_port *port, int dtr, int rts)
2026-03-03T18:33:59.0451099Z       |     ^~~~~~~~~~~~~~~~
2026-03-03T18:33:59.0576591Z   LD [M]  drivers/thunderbolt/thunderbolt.o
2026-03-03T18:33:59.0604836Z   CC [M]  drivers/iio/gyro/itg3200_buffer.o
2026-03-03T18:33:59.0740430Z   CC [M]  drivers/net/ethernet/sfc/siena/ptp.o
2026-03-03T18:33:59.0770243Z   CC [M]  drivers/infiniband/core/uverbs_std_types_flow_action.o
2026-03-03T18:33:59.0772111Z   CC [M]  drivers/iio/potentiometer/mcp4131.o
2026-03-03T18:33:59.0794107Z   CC [M]  drivers/gpu/drm/nouveau/nvkm/falcon/ga100.o
2026-03-03T18:33:59.0980208Z   CC [M]  drivers/hid/hid-gaff.o
2026-03-03T18:33:59.1290616Z   CC [M]  drivers/net/usb/pegasus.o
2026-03-03T18:33:59.1417260Z   CC [M]  drivers/iio/dac/ad5592r-base.o
2026-03-03T18:33:59.1474619Z   CC [M]  drivers/net/bonding/bond_debugfs.o
2026-03-03T18:33:59.1658293Z   CC [M]  drivers/gpu/drm/amd/amdgpu/amdgpu_virt.o
2026-03-03T18:33:59.1873610Z   CC [M]  drivers/net/ieee802154/adf7242.o
2026-03-03T18:33:59.1915250Z   CC [M]  drivers/gpu/drm/i915/gt/intel_execlists_submission.o
2026-03-03T18:33:59.1918103Z   CC [M]  drivers/media/dvb-frontends/ts2020.o
2026-03-03T18:33:59.1965925Z cc1: all warnings being treated as errors
2026-03-03T18:33:59.2049881Z   CC [M]  drivers/gpu/drm/nouveau/nvkm/falcon/ga102.o

Fixes: eb337d3f4185 ("drivers: net: wwan: add simple DTR driver")
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>