uart: phytium: Switch to irq_get_nr_irqs()
Log:
drivers/tty/serial/phytium-uart.c:728:34: error: use of undeclared identifier 'nr_irqs'
  728 |         if (ser->irq < 0 || ser->irq >= nr_irqs)
      |                                         ^

Link: https://github.com/deepin-community/kernel/pull/150
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>