x86/fpu: Add missing <linux/thread_info.h> include to api.h
The sched.h dependency pruning series (cherry-picked from v6.8-rc1)
severed the transitive include chain that previously brought
<linux/thread_info.h> into arch/x86/include/asm/fpu/api.h.

The Hygon LMC non-atomic FPU code path in api.h calls
check_using_kernel_fpu(), which uses test_thread_flag() (defined in
<linux/thread_info.h>) and TIF_USING_FPU_NONATOMIC (defined in
<asm/thread_info.h>, pulled in transitively by
<linux/thread_info.h>). Once the transitive chain was cut, both
symbols became undeclared and the compiler emitted, e.g. when building
drivers/gpu/drm/i915/i915_memcpy.c:

  ./arch/x86/include/asm/fpu/api.h:81:22: error: implicit declaration
  of function 'test_thread_flag'
  ./arch/x86/include/asm/fpu/api.h:81:39: error:
  'TIF_USING_FPU_NONATOMIC' undeclared

Fix it by adding an explicit #include <linux/thread_info.h> to
arch/x86/include/asm/fpu/api.h, so that the header directly includes
the header that defines the symbols it uses, rather than depending on a
fragile, config-sensitive transitive include chain.

Assisted-By: AtomCode:GLM-5.2
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>