uart: phytium: Remove deprecated PCI functions
pcim_iomap_table() and pcim_iomap_regions_request_all() have been
deprecated by the PCI subsystem in commit e354bb84a4c1 ("PCI: Deprecate
pcim_iomap_table(), pcim_iomap_regions_request_all()").

Replace these functions with their successors, pcim_iomap() and
pcim_request_all_regions()

Log:
drivers/tty/serial/phytium-uart.c:834:7: error: call to undeclared function 'pcim_iomap_regions_request_all'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  834 |         rc = pcim_iomap_regions_request_all(pdev, 0x01, pci_name(pdev));
      |              ^
1 error generated.

Link: https://github.com/deepin-community/kernel/pull/150
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>