selftests: drv-net: Bring back tool() to driver __init__s
[ Upstream commit 353cfc0ef3f34ef7fe313ae38dac37f2454a7cf5 ]

The pp_alloc_fail.py test (which doesn't run in NIPA CI?) uses tool, add
back the import.

Resolves:
  ImportError: cannot import name 'tool' from 'lib.py'

Fixes: 68a052239fc4 ("selftests: drv-net: update remaining Python init files")
Reviewed-by: Nimrod Oren <noren@nvidia.com>
Signed-off-by: Gal Pressman <gal@nvidia.com>
Link: https://patch.msgid.link/20260105163319.47619-1-gal@nvidia.com
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>
(cherry picked from commit 334bbbbf4c809c31722b5cae6c2158d9ff2fdc9f)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>