Reapply "binder: Export close_fd_get_file and can_nice"
binder: Export close_fd_get_file and can_nice

Fix follow compile errors:
ERROR: modpost: "close_fd_get_file" [drivers/android/binder_linux.ko] undefined!
ERROR: modpost: "can_nice" [drivers/android/binder_linux.ko] undefined!

Signed-off-by: WangYuli <wangyuli@uniontech.com>
This reverts commit 3f86bbf3820cf65cf83f902512625ddb165f1781.

Signed-off-by: Wentao Guan <guanwentao@uniontech.com>