futex/pi: Add missing <linux/hrtimer.h> include
The "hrtimers: Split out hrtimer_types.h" commit (cherry-picked from
upstream 50d91c765825) replaced <linux/hrtimer.h> with
<linux/hrtimer_types.h> in sched.h, in order to trim down sched.h's
transitive header dependencies.

This had an unintended side effect on kernel/futex/pi.c: the file uses
a number of hrtimer symbols whose definitions live in <linux/hrtimer.h>,
but pi.c relied on the old sched.h -> ... -> <linux/hrtimer.h> implicit
inclusion chain to bring in those declarations. Once sched.h switched
to the minimal <linux/hrtimer_types.h>, that transitive path was
severed and the compiler emitted:

  kernel/futex/pi.c:921:32: error: storage size of 'timeout' isn't known
  kernel/futex/pi.c:1033:17: error: implicit declaration of function
  'hrtimer_sleeper_start_expires'
  kernel/futex/pi.c:1091:17: error: implicit declaration of function
  'hrtimer_cancel'
  kernel/futex/pi.c:1092:17: error: implicit declaration of function
  'destroy_hrtimer_on_stack'
  kernel/futex/pi.c:1033:51: error: 'HRTIMER_MODE_ABS' undeclared

Fix it by adding an explicit #include <linux/hrtimer.h> to
kernel/futex/pi.c, so that the file directly includes the header that
defines the symbols it uses, rather than depending on a fragile,
config-sensitive transitive include chain.

Assisted-By: AtomCode:GLM-5.2
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>