sw64: lpc: fix compile error with CONFIG_SUNWAY_SUPERIO_AST2400=y
This patch fixes undefined reference to DRIVER_NAME.

Signed-off-by: Xu Chenjiao <xuchenjiao@wxiat.com>
Reviewed-by: He Sheng <hesheng@wxiat.com>
Signed-off-by: Gu Zitao <guzitao@wxiat.com>
(cherry picked from commit 81d0f28780498077e617f901d27c0d0e43076c71)