mailbox: phytium_mailbox: Convert to platform remove callback returning void
0edb555: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

Log:
drivers/mailbox/phytium_mailbox.c:184:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  184 |         .remove = phytium_mbox_remove,
      |                   ^~~~~~~~~~~~~~~~~~~
drivers/mailbox/phytium_mailbox.c:184:19: note: (near initialization for ‘phytium_mbox_driver.<anonymous>.remove’)

(cherry picked from commit 29d3b752bfc9a2baf11981b10659f321a26b67f0)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>