phytium: phytmac: fix build with clang
Log:
drivers/net/ethernet/phytium/phytmac_platform.c:232:8: error: variable 'ret' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
  232 |                         if (!pdata->msg_regs) {
      |                             ^~~~~~~~~~~~~~~~
drivers/net/ethernet/phytium/phytmac_platform.c:311:9: note: uninitialized use occurs here
  311 |         return ret;
      |                ^~~
drivers/net/ethernet/phytium/phytmac_platform.c:232:4: note: remove the 'if' if its condition is always false
  232 |                         if (!pdata->msg_regs) {
      |                         ^~~~~~~~~~~~~~~~~~~~~~~
  233 |                                 dev_err(&pdev->dev, "msg_regs ioremap failed, i=%d\n", i);
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  234 |                                 goto err_mem;
      |                                 ~~~~~~~~~~~~~
  235 |                         }
      |                         ~
drivers/net/ethernet/phytium/phytmac_platform.c:172:9: note: initialize the variable 'ret' to silence this warning
  172 |         int ret, i;
      |                ^
      |                 = 0
1 error generated.
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>

(cherry picked from commit c69ebe810cdee4f00d0b165d6ee4b111e858d224)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>