crypto: ccp: Fix compile error on csv_cmd_buffer_len()
hygon inclusion
category: bugfix
CVE: NA

---------------------------

The error messages is shown as following:

drivers/crypto/ccp/hygon/csv-dev.c:21:5: error: no previous prototype for ‘csv_cmd_buffer_len’ [-Werror=missing-prototypes]
   21 | int csv_cmd_buffer_len(int cmd)
      |     ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Reported-by: WangYuli <wangyuli@uniontech.com>
Signed-off-by: hanliyang <hanliyang@hygon.cn>
Link: https://github.com/deepin-community/kernel/pull/351
(cherry picked from commit 47ea01f1301152f3e06a98126235351280165fd4)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>