can: phytium: Convert to platform remove callback returning void
0edb555: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

Log:
drivers/net/can/phytium/phytium_can_platform.c:220:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  220 |         .remove = phytium_can_plat_remove,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~
drivers/net/can/phytium/phytium_can_platform.c:220:19: note: (near initialization for ‘phytium_can_plat_driver.<anonymous>.remove’)

(cherry picked from commit ca9434f201a706488a13765c7cdf04f532cabce3)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>