tools: fix build failed with redefined MASK
deepin inclusion
category: bugfix

Found when build perf failed.

Log:
/home/deepin/kernel/tools/arch/x86/include/asm/required-features.h:105: error: "REQUIRED_MASK_CHECK" redefined [-Werror]
  105 | #define REQUIRED_MASK_CHECK BUILD_BUG_ON_ZERO(NCAPINTS != 23)
      |
/home/deepin/kernel/tools/arch/x86/include/asm/required-features.h:103: note: this is the location of the previous definition
  103 | #define REQUIRED_MASK_CHECK BUILD_BUG_ON_ZERO(NCAPINTS != 22)
      |
In file included from /home/deepin/kernel/tools/arch/x86/include/asm/cpufeatures.h:10:
/home/deepin/kernel/tools/arch/x86/include/asm/disabled-features.h:161: error: "DISABLED_MASK_CHECK" redefined [-Werror]
  161 | #define DISABLED_MASK_CHECK BUILD_BUG_ON_ZERO(NCAPINTS != 23)
      |
/home/deepin/kernel/tools/arch/x86/include/asm/disabled-features.h:159: note: this is the location of the previous definition
  159 | #define DISABLED_MASK_CHECK BUILD_BUG_ON_ZERO(NCAPINTS != 22)
      |
cc1: all warnings being treated as errors
make[4]: *** [/home/deepin/kernel/tools/build/Makefile.build:114：bench/mem-memcpy-x86-64-asm.o] 错误 1
make[4]: *** 正在等待未完成的任务....
In file included from /home/deepin/kernel/tools/arch/x86/include/asm/cpufeatures.h:6,
                 from bench/../../arch/x86/lib/memset_64.S:6,
                 from bench/mem-memset-x86-64-asm.S:8:
/home/deepin/kernel/tools/arch/x86/include/asm/required-features.h:105: error: "REQUIRED_MASK_CHECK" redefined [-Werror]
  105 | #define REQUIRED_MASK_CHECK BUILD_BUG_ON_ZERO(NCAPINTS != 23)
      |
/home/deepin/kernel/tools/arch/x86/include/asm/required-features.h:103: note: this is the location of the previous definition
  103 | #define REQUIRED_MASK_CHECK BUILD_BUG_ON_ZERO(NCAPINTS != 22)
      |
In file included from /home/deepin/kernel/tools/arch/x86/include/asm/cpufeatures.h:10:
/home/deepin/kernel/tools/arch/x86/include/asm/disabled-features.h:161: error: "DISABLED_MASK_CHECK" redefined [-Werror]
  161 | #define DISABLED_MASK_CHECK BUILD_BUG_ON_ZERO(NCAPINTS != 23)
      |
/home/deepin/kernel/tools/arch/x86/include/asm/disabled-features.h:159: note: this is the location of the previous definition
  159 | #define DISABLED_MASK_CHECK BUILD_BUG_ON_ZERO(NCAPINTS != 22)
      |

Fixes: 89b2806e0bb3d ("x86/delay: add support for Zhaoxin ZXPAUSE instruction")
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>