net: stmmac: phytium: remove lpi_irq
deepin inclusion
category: bugfix

commit 8096f0383425 ("net: stmmac: remove support for lpi_intr_o") upstream,
so remove it.

Log:
2026-03-13T04:27:16.4756517Z drivers/net/ethernet/stmicro/stmmac/dwmac-phytium.c: In function ‘phytium_dwmac_probe’:
2026-03-13T04:27:16.4826467Z drivers/net/ethernet/stmicro/stmmac/dwmac-phytium.c:188:19: error: ‘struct stmmac_resources’ has no member named ‘lpi_irq’
2026-03-13T04:27:16.4828875Z   CC [M]  drivers/target/iscsi/iscsi_target.o
2026-03-13T04:27:16.4865576Z   188 |         stmmac_res.lpi_irq = -1;
2026-03-13T04:27:16.4894805Z       |                   ^
2026-03-13T04:27:16.5094162Z   CC [M]  drivers/mtd/nand/raw/nand_onfi.o

Signed-off-by: Wentao Guan <guanwentao@uniontech.com>