eth: phytmac: phytmac_ioctl: Return -EOPNOTSUPP by default
Fix follow error with clang-19:

drivers/net/ethernet/phytium/phytmac_main.c:1818:2: error: variable 'ret' is used uninitialized whenever switch default is taken [-Werror,-Wsometimes-uninitialized]
 1818 |         default:
      |         ^~~~~~~
drivers/net/ethernet/phytium/phytmac_main.c:1822:9: note: uninitialized use occurs here
 1822 |         return ret;
      |                ^~~
drivers/net/ethernet/phytium/phytmac_main.c:1799:9: note: initialize the variable 'ret' to silence this warning
 1799 |         int ret;
      |                ^
      |                 = 0
1 error generated.

Signed-off-by: WangYuli <wangyuli@uniontech.com>
Link: https://github.com/deepin-community/kernel/pull/504
(cherry picked from commit 8ccf12901858567765ac99d87332f0111de1ba7d)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>