char: phytnetled: Fix compilation errors caused by disabling CONFIG_ACPI
Disabling CONFIG_ACPI will cause errors like 'error: implicit
declaration of function ‘acpi_get_acpi_dev’', so it is necessary
to add #ifdef CONFIG_ACPI for protection.

Signed-off-by: Ma Mingrui <mamingrui1243@phytium.com.cn>
Signed-off-by: Li Tongfeng <litongfeng1497@phytium.com.cn>
Signed-off-by: Wang Yinfeng <wangyinfeng@phytium.com.cn>