net: mhi: Drop the MHI auto_queue feature for IPCR DL channels
deepin inclusion
category: bugfix

commit e296c42280f5 ("net: qrtr: Drop the MHI auto_queue feature for IPCR DL channels") upstream,
so remove AUTOQUEUE for fn980v2,fn990.

2026-03-13T01:50:28.9880491Z drivers/bus/mhi/host/pci_generic.c:807:9: error: implicit declaration of function ‘MHI_CHANNEL_CONFIG_DL_AUTOQUEUE’; did you mean ‘MHI_CHANNEL_CONFIG_DL_FP’? [-Werror=implicit-function-declaration]
2026-03-13T01:50:28.9883549Z   807 |         MHI_CHANNEL_CONFIG_DL_AUTOQUEUE(19, "IP_CTRL", 8, 1),
2026-03-13T01:50:28.9884407Z       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2026-03-13T01:50:28.9885012Z       |         MHI_CHANNEL_CONFIG_DL_FP
2026-03-13T01:50:28.9886563Z drivers/bus/mhi/host/pci_generic.c:807:9: error: initialization of ‘char *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>