mtd: phytium: Resolve some errors when '-Werror' was enabled
This patch resolves some errors when '-Werror' was enabled

Signed-off-by: yuanxia <yuanxia2073@phytium.com.cn>
Signed-off-by: Wang Hanmo <wanghanmo2242@phytium.com.cn>
Link: https://github.com/deepin-community/kernel/pull/233
[ fixed for v6.18 ]
Log:
drivers/mtd/parsers/acpipart_core.c:35:35: error: variable 'child_handle' is uninitialized when used here [-Werror,-Wuninitialized]
   35 |                 device_get_next_child_node(dev, child_handle);
      |                                                 ^~~~~~~~~~~~
drivers/mtd/parsers/acpipart_core.c:27:36: note: initialize the variable 'child_handle' to silence this warning
   27 |         struct fwnode_handle *child_handle;
      |                                           ^
      |                                            = NULL
1 error generated.
(cherry picked from commit c1de28d10f4873ce460cc13f04a0e3e4d154bbb1)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>