sw64: kvm: fix build failure about KVM
This patch:

 - built in kvm_cma.c to fix:
   arch/sw_64/mm/init.o: In function `sw64_kvm_reserve':
   (.init.text+0x424): undefined reference to `kvm_cma_declare_contiguous'

 - use Makefile.kvm for common files to avoid:
   virt/kvm/kvm_main.o: In function `kvm_vcpu_stats_read':
   (.text+0x3da4): undefined reference to `kvm_stats_read'

Signed-off-by: Min Fanlei <minfanlei@wxiat.com>
Reviewed-by: He Sheng <hesheng@wxiat.com>
Signed-off-by: Gu Zitao <guzitao@wxiat.com>
(cherry picked from commit 32b191d3cf3f9f5b57315f779f64eb808a29238b)