eth: yt6801: donot assigning value of variable of type to itself
Fix follow compile errors with clang-19:

drivers/net/ethernet/motorcomm/yt6801/fuxi-gmac-hw.c:500:8: error: explicitly assigning value of variable of type 'struct fxgmac_pdata *' to itself [-Werror,-Wself-assign]
  500 |         pdata = pdata;
      |         ~~~~~ ^ ~~~~~
drivers/net/ethernet/motorcomm/yt6801/fuxi-gmac-hw.c:611:8: error: explicitly assigning value of variable of type 'struct fxgmac_pdata *' to itself [-Werror,-Wself-assign]
  611 |         pdata = pdata;
      |         ~~~~~ ^ ~~~~~
drivers/net/ethernet/motorcomm/yt6801/fuxi-gmac-hw.c:1321:14: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
 1321 |         start_index = start_index;
      |         ~~~~~~~~~~~ ^ ~~~~~~~~~~~
drivers/net/ethernet/motorcomm/yt6801/fuxi-gmac-hw.c:1618:8: error: explicitly assigning value of variable of type 'struct fxgmac_pdata *' to itself [-Werror,-Wself-assign]
 1618 |         pdata = pdata;
      |         ~~~~~ ^ ~~~~~
drivers/net/ethernet/motorcomm/yt6801/fuxi-gmac-hw.c:2628:7: error: explicitly assigning value of variable of type 'unsigned int' to itself [-Werror,-Wself-assign]
 2628 |         type = type;
      |         ~~~~ ^ ~~~~
drivers/net/ethernet/motorcomm/yt6801/fuxi-gmac-hw.c:5019:9: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
 5019 |         int_id = int_id;
      |         ~~~~~~ ^ ~~~~~~
6 errors generated.

Signed-off-by: WangYuli <wangyuli@uniontech.com>
(cherry picked from commit 0666221c183beb16e84394a3fb176a42d68fc549)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>