deepin: arm64: acpi: hisi: mm/ioremap: pass pgprot_t to ioremap_prot() instead of unsigned long
commit 86758b504864913233f6a16076184ba784cd4466
Author: Ryan Roberts <ryan.roberts@arm.com>
Date:   Tue Feb 18 15:49:54 2025 +0530

    mm/ioremap: pass pgprot_t to ioremap_prot() instead of unsigned long

    ioremap_prot() currently accepts pgprot_val parameter as an unsigned long,
    thus implicitly assuming that pgprot_val and pgprot_t could never be
    bigger than unsigned long.  But this assumption soon will not be true on
    arm64 when using D128 pgtables.  In 128 bit page table configuration,
    unsigned long is 64 bit, but pgprot_t is 128 bit.

    Passing platform abstracted pgprot_t argument is better as compared to
    size based data types.  Let's change the parameter to directly pass
    pgprot_t like another similar helper generic_ioremap_prot().

    Without this change in place, D128 configuration does not work on arm64 as
    the top 64 bits gets silently stripped when passing the protection value
    to this function.

    Link: https://lkml.kernel.org/r/20250218101954.415331-1-anshuman.khandual@arm.com
    Signed-off-by: Ryan Roberts <ryan.roberts@arm.com>
    Co-developed-by: Anshuman Khandual <anshuman.khandual@arm.com>
    Signed-off-by: Anshuman Khandual <anshuman.khandual@arm.com>
    Acked-by: Catalin Marinas <catalin.marinas@arm.com> [arm64]
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>

Log:
arch/arm64/kernel/acpi.c:308:48: error: passing 'ptdesc_t' (aka 'unsigned long long') to parameter of incompatible type 'pgprot_t'
  308 |                return ioremap_prot(phys, size, pgprot_val(__acpi_get_mem_attribute(phys)));
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./arch/arm64/include/asm/pgtable-types.h:58:23: note: expanded from macro 'pgprot_val'
   58 | #define pgprot_val(x)   ((x).pgprot)
      |                         ^~~~~~~~~~~~
./include/asm-generic/io.h:1148:16: note: passing argument to parameter 'prot' here
 1148 |                            pgprot_t prot);
      |                                     ^

Signed-off-by: Wentao Guan <guanwentao@uniontech.com>