irqchip/gic-phytium-2500: Remove sync_access callback and make distributor priorities variables
Fix compile error during the two upstream commits:
commit:
a6156e70316: irqchip/gic-v3: Make distributor priorities variables
e95c64a7fb71: irqchip/gic-common: Remove sync_access callback

Log:
drivers/irqchip/irq-gic-phytium-2500.c: In function ‘gic_dist_init’:
drivers/irqchip/irq-gic-phytium-2500.c:948:40: error: ‘GICD_INT_DEF_PRI_X4’ undeclared (first use in this function); did you mean ‘GICD_INT_DEF_PRI’?
  948 |                         writel_relaxed(GICD_INT_DEF_PRI_X4, base + GICD_IPRIORITYRnE + i);
      |                                        ^~~~~~~~~~~~~~~~~~~
      |                                        GICD_INT_DEF_PRI
drivers/irqchip/irq-gic-phytium-2500.c:948:40: note: each undeclared identifier is reported only once for each function it appears in
In file included from ./include/uapi/linux/posix_types.h:5,
                 from ./include/uapi/linux/types.h:14,
                 from ./include/linux/types.h:6,
                 from ./include/linux/kasan-checks.h:5,
                 from ./include/asm-generic/rwonce.h:26,
                 from ./arch/arm64/include/asm/rwonce.h:71,
                 from ./include/linux/compiler.h:317,
                 from ./include/linux/build_bug.h:5,
                 from ./include/linux/bits.h:22,
                 from ./include/linux/ioport.h:13,
                 from ./include/linux/acpi.h:12,
                 from drivers/irqchip/irq-gic-phytium-2500.c:8:
./include/linux/stddef.h:8:14: error: passing argument 3 of ‘gic_dist_config’ makes integer from pointer without a cast [-Werror=int-conversion]
    8 | #define NULL ((void *)0)
      |              ^~~~~~~~~~~
      |              |
      |              void *
drivers/irqchip/irq-gic-phytium-2500.c:951:52: note: in expansion of macro ‘NULL’
  951 |                 gic_dist_config(base, GIC_LINE_NR, NULL);
      |                                                    ^~~~
In file included from drivers/irqchip/irq-gic-phytium-2500.c:31:
drivers/irqchip/irq-gic-common.h:25:59: note: expected ‘u8’ {aka ‘unsigned char’} but argument is of type ‘void *’
   25 | void gic_dist_config(void __iomem *base, int gic_irqs, u8 priority);
      |                                                        ~~~^~~~~~~~
drivers/irqchip/irq-gic-phytium-2500.c: In function ‘gic_cpu_init’:
drivers/irqchip/irq-gic-phytium-2500.c:1298:9: error: too few arguments to function ‘gic_cpu_config’
 1298 |         gic_cpu_config(rbase, gic_data.ppi_nr + 16);
      |         ^~~~~~~~~~~~~~
drivers/irqchip/irq-gic-common.h:26:6: note: declared here
   26 | void gic_cpu_config(void __iomem *base, int nr, u8 priority);
      |      ^~~~~~~~~~~~~~
./include/linux/stddef.h:8:14: error: passing argument 3 of ‘gic_cpu_config’ makes integer from pointer without a cast [-Werror=int-conversion]
    8 | #define NULL ((void *)0)
      |              ^~~~~~~~~~~
      |              |
      |              void *
drivers/irqchip/irq-gic-phytium-2500.c:1310:69: note: in expansion of macro ‘NULL’
 1310 |                         gic_cpu_config(rbase, gic_data.ppi_nr + 16, NULL);
      |                                                                     ^~~~
drivers/irqchip/irq-gic-common.h:26:52: note: expected ‘u8’ {aka ‘unsigned char’} but argument is of type ‘void *’
   26 | void gic_cpu_config(void __iomem *base, int nr, u8 priority);
      |                                                 ~~~^~~~~~~~
cc1: all warnings being treated as errors
make[7]: *** [scripts/Makefile.build:229：drivers/irqchip/irq-gic-phytium-2500.o] 错误 1
make[6]: *** [scripts/Makefile.build:478：drivers/irqchip] 错误 2
make[5]: *** [scripts/Makefile.build:478：drivers] 错误 2

(cherry picked from commit 53ce2f41ee2bd92c55c5f1da75cbe40e963984ea)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>