sw64: kvm: fix link error with CONFIG_KVM=m
Move kvm_cma.c to the arch/sw_64/kernel/ directory to fix:

arch/sw_64/kvm/kvm_cma.o: In function `kvm_cma_init_reserved_areas':
(.init.text+0x0): multiple definition of `init_module'
arch/sw_64/kvm/kvm_core3.o:(.init.text+0x68): first defined here
scripts/Makefile.build:438: recipe for target 'arch/sw_64/kvm/kvm.o' failed
make[4]: *** [arch/sw_64/kvm/kvm.o] Error 1

Signed-off-by: Min Fanlei <minfanlei@wxiat.com>
Reviewed-by: He Sheng <hesheng@wxiat.com>
Signed-off-by: Gu Zitao <guzitao@wxiat.com>
(cherry picked from commit c5c1d0560da4ce7097f6d79a7cc9319617a9090c)