net: ethernet: phytium: add a missing declaration for *np
Fix a compilation error:

drivers/net/ethernet/phytium/phytmac_platform.c: In function ‘phytmac_plat_probe’:
drivers/net/ethernet/phytium/phytmac_platform.c:98:55: error: ‘np’ undeclared (first use in this function); did you mean ‘up’?
   98 |                 match = of_match_node(phytmac_dt_ids, np);
      |                                                       ^~
      |                                                       up

Signed-off-by: Mingcong Bai <baimingcong@uniontech.com>
Link: https://github.com/deepin-community/kernel/pull/222
(cherry picked from commit d5c088136d03e855fd43ea10ac683f81575112ef)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>