net: mucse: rnpm: Fix build error frame-larger-than
The fix is similar to file rnpgbe/rnpgbe_main.c rnpgbe_rx_ring_reinit‎.

The reason is the temp_ring var is too large than frame size.

Log:
drivers/net/ethernet/mucse/rnpm/rnpm_main.c: In function ‘rnpm_rx_ring_reinit.isra’:
drivers/net/ethernet/mucse/rnpm/rnpm_main.c:1299:1: error: the frame size of 8192 bytes is larger than 4096 bytes [-Werror=frame-larger-than=]
1299 | }

Signed-off-by: Wentao Guan <guanwentao@outlook.com>