drm: cix: linlondp: minmax: convert to MAX_T
deepin inclusion
category: bugfix

After v6.6.109 update minmax.h cause the driver build err.
Fix it.

Log:

drivers/gpu/drm/cix/linlon-dp/linlondp_wb_connector.c: In function ‘linlondp_wb_connector_create_color_prop’:
drivers/gpu/drm/cix/linlon-dp/linlondp_wb_connector.c:288:16: error: ISO C90 forbids variable length array ‘enum_list’ [-Werror=vla]
  288 |         struct drm_prop_enum_list enum_list[max_t(int, DRM_COLOR_ENCODING_MAX,
      |                ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Fixes: 3a7e02c040b1 ("minmax: avoid overly complicated constant expressions in VM code")
Fixes: 4477b39c32fd ("minmax: add a few more MIN_T/MAX_T users")
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>