LoongArch: BPI: Declare acpi_arch_init with a void prototype
Fix follow error with clang-19:

arch/loongarch/kernel/legacy_boot.c:687:28: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
  687 | void __init acpi_arch_init (){
      |                            ^
      |                             void
1 error generated.

Signed-off-by: WangYuli <wangyuli@uniontech.com>
Link: https://github.com/deepin-community/kernel/pull/502
(cherry picked from commit dd65caaed71b559f5fc4ca64cc313c76e62eb0cd)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>