crypto: ccp: Fix compile error on file csv-dev.h
hygon inclusion
category: bugfix
CVE: NA

---------------------------

The error messages is shown as following:

In file included from drivers/crypto/ccp/hygon/csv-dev.c:19:
drivers/crypto/ccp/hygon/csv-dev.h:18:36: error: ‘struct sev_user_data_status’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
   18 | void csv_update_api_version(struct sev_user_data_status *status);
      |                                    ^~~~~~~~~~~~~~~~~~~~
drivers/crypto/ccp/hygon/csv-dev.c:34:6: error: conflicting types for ‘csv_update_api_version’; have ‘void(struct sev_user_data_status *)’
   34 | void csv_update_api_version(struct sev_user_data_status *status)
      |      ^~~~~~~~~~~~~~~~~~~~~~
drivers/crypto/ccp/hygon/csv-dev.h:18:6: note: previous declaration of ‘csv_update_api_version’ with type ‘void(struct sev_user_data_status *)’
   18 | void csv_update_api_version(struct sev_user_data_status *status);
      |      ^~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Signed-off-by: hanliyang <hanliyang@hygon.cn>
Link: https://github.com/deepin-community/kernel/pull/353
(cherry picked from commit 174941c5dfd6d07fe998b6ec6b111a7be8f1c5c3)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>