net: stmmac: remove support for lpi_intr_o
deepin inclusion
from stable-v6.6.130
category: bugfix

commit 14eb64db8ff07b58a35b98375f446d9e20765674 upstream.

The dwmac databook for v3.74a states that lpi_intr_o is a sideband
signal which should be used to ungate the application clock, and this
signal is synchronous to the receive clock. The receive clock can run
at 2.5, 25 or 125MHz depending on the media speed, and can stop under
the control of the link partner. This means that the time it takes to
clear is dependent on the negotiated media speed, and thus can be 8,
40, or 400ns after reading the LPI control and status register.

It has been observed with some aggressive link partners, this clock
can stop while lpi_intr_o is still asserted, meaning that the signal
remains asserted for an indefinite period that the local system has
no direct control over.

The LPI interrupts will still be signalled through the main interrupt
path in any case, and this path is not dependent on the receive clock.

This, since we do not gate the application clock, and the chances of
adding clock gating in the future are slim due to the clocks being
ill-defined, lpi_intr_o serves no useful purpose. Remove the code which
requests the interrupt, and all associated code.

Reported-by: Ovidiu Panait <ovidiu.panait.rb@renesas.com>
Tested-by: Ovidiu Panait <ovidiu.panait.rb@renesas.com> # Renesas RZ/V2H board
Signed-off-by: Russell King (Oracle) <rmk+kernel@armlinux.org.uk>
Link: https://patch.msgid.link/E1vnJbt-00000007YYN-28nm@rmk-PC.armlinux.org.uk
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
Signed-off-by: Ovidiu Panait <ovidiu.panait.rb@renesas.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
[net: stmmac: phytium: remove lpi_irq
    commit 8096f0383425 ("net: stmmac: remove support for lpi_intr_o") upstream,
    so remove it.
    Log:
    drivers/net/ethernet/stmicro/stmmac/dwmac-phytium.c: In function ‘phytium_dwmac_probe’:
    drivers/net/ethernet/stmicro/stmmac/dwmac-phytium.c:188:19: error: ‘struct stmmac_resources’ has no member named ‘lpi_irq’
    188 |         stmmac_res.lpi_irq = -1;]
(cherry picked from commit 268fd550228195eddadb93ac293d5458ee4c3615)
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>

Conflicts:
	drivers/net/ethernet/stmicro/stmmac/dwmac-loongson.c